[package]
name = "pyhanko-lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
lambda_runtime = "0.14.4"
serde_json = "1.0.145"
tokio = "1.47.1"
zip = "5.1.1"

[build-dependencies]
walkdir = "2.5.0"
zip = "5.1.1"
