name: Build-arm

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v5.0.0
      - name: Install Zig
        run: npm install -g @ziglang/cli
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-lambda from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-lambda
      - uses: Swatinem/rust-cache@v2
      - run: |
          export PYO3_CONFIG_FILE=$PWD/pyo3.config
          cargo lambda build
      - uses: actions/upload-artifact@v4
        with:
          path: ./target/lambda
